name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        include:
          - os: windows-latest
            cmake-args: -A x64
          - os: ubuntu-latest
            cmake-args: -G Ninja

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y cmake ninja-build g++

      - name: Build
        run: |
          cmake ${{ matrix.cmake-args }} -B build -DCMAKE_BUILD_TYPE=Release -DTIMEDURATION_BUILD_TESTS=ON
          cmake --build build --config Release

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
