name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
      runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake ninja-build g++

      - name: Configure (with tests)
        run: cmake -B build -G Ninja -DTIMEDURATION_BUILD_TESTS=ON

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
